-- Database: MySQL

CREATE DATABASE bank;
USE bank;

CREATE TABLE user (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(127) NOT NULL,
    password VARCHAR(127) NOT NULL,
    balance DOUBLE NOT NULL DEFAULT 0
);